In [31]:
#import libraries
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.tag import pos_tag
from textblob import TextBlob

In [32]:
# Load the dataset
df = pd.read_csv('Twitter_Reviews.csv')

In [33]:
#Print first 5 rows of dataset
df.head()

,Review_Id,User_Name,User_Image,Comment,Thumbs_Up_Count,Version,Review_Created_At,Sort_Order
0,d80a474e-421c-408e-aa49-b06185a3830a,Sean Rollins,https://play-lh.googleusercontent.com/a-/ACNPE...,Twitter's obsession with turning itself into t...,7121,9.65.0-release.0,28-10-2022 01:48,most_relevant
1,adce2dfc-11d4-43e0-b4b3-891d942a3457,Andrew Pike,https://play-lh.googleusercontent.com/a-/ACNPE...,Absolute rubbish. It still keeps refreshing af...,4833,9.56.2-release.0,26-08-2022 08:26,most_relevant
2,205b4fe2-50f6-4cbd-b63a-d6a3722dfa24,Dean Hampton,https://play-lh.googleusercontent.com/a/ALm5wu...,The most recent update has ruined this app. Th...,2409,9.56.2-release.0,26-08-2022 18:31,most_relevant
3,2b18dec4-3094-4539-8f6e-dc51fe62fb21,Dave,https://play-lh.googleusercontent.com/a/ALm5wu...,No closed caption (cc) button is present to di...,4033,9.56.2-release.0,26-08-2022 16:05,most_relevant
4,426d8c6f-df41-459d-936c-eea1154af0b8,Royce Miller,https://play-lh.googleusercontent.com/a-/ACNPE...,This app is frustrating as heck. When you're s...,1671,9.57.0-release.1,02-09-2022 07:37,most_relevant

In [34]:
# Tokenization
df['Tokens'] = df['Comment'].apply(lambda x: word_tokenize(x))

In [35]:
# POS tagging
df['POS_tags'] = df['Tokens'].apply(lambda x: pos_tag(x))

In [37]:
# Sentiment analysis
df['Sentiment'] = df['Comment'].apply(lambda x: TextBlob(x).sentiment.polarity)

In [38]:
# Function to classify sentiment based on polarity score
def classify_sentiment(score):
    if score > 0:
        return 'Positive'
    elif score < 0:
        return 'Negative'
    else:
        return 'Neutral'

In [40]:
# Classify sentiment using polarity score
df['Sentiment_Classification'] = df['Sentiment'].apply(classify_sentiment)

In [42]:
# Print the updated dataframe
df[['Comment', 'Tokens', 'POS_tags', 'Sentiment', 'Sentiment_Classification']]

,Comment,Tokens,POS_tags,Sentiment,Sentiment_Classification
0,Twitter's obsession with turning itself into t...,"[Twitter, 's, obsession, with, turning, itself...","[(Twitter, NNP), ('s, POS), (obsession, NN), (...",0.140741,Positive
1,Absolute rubbish. It still keeps refreshing af...,"[Absolute, rubbish, ., It, still, keeps, refre...","[(Absolute, NNP), (rubbish, NN), (., .), (It, ...",0.130000,Positive
2,The most recent update has ruined this app. Th...,"[The, most, recent, update, has, ruined, this,...","[(The, DT), (most, RBS), (recent, JJ), (update...",-0.036071,Negative
3,No closed caption (cc) button is present to di...,"[No, closed, caption, (, cc, ), button, is, pr...","[(No, DT), (closed, JJ), (caption, NN), ((, ()...",0.034280,Positive
4,This app is frustrating as heck. When you're s...,"[This, app, is, frustrating, as, heck, ., When...","[(This, DT), (app, NN), (is, VBZ), (frustratin...",-0.151852,Negative
...,...,...,...,...,...
1195,graet,[graet],"[(graet, NN)]",0.000000,Neutral
1196,I like,"[I, like]","[(I, PRP), (like, VBP)]",0.000000,Neutral
1197,Great app,"[Great, app]","[(Great, NNP), (app, NN)]",0.800000,Positive
1198,5 star for Elon Musk ✌️,"[5, star, for, Elon, Musk, ✌️]","[(5, CD), (star, NN), (for, IN), (Elon, NNP), ...",0.000000,Neutral
1199,Nice app,"[Nice, app]","[(Nice, NNP), (app, NN)]",0.600000,Positive